name: Python package

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Run tests
        run: |
          python -m pip install tox
          python -m tox -e py

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}-wheel-${{ matrix.python }}
          path: dist/*.whl
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .tox/coverage.xml
          #flags: unittests # optional
          #name: codecov-umbrella # optional
          #fail_ci_if_error: true # optional (default = false)
          #verbose: true # optional (default = false)
        if: matrix.python == '3.11' && matrix.os == 'ubuntu-latest'
